#!/usr/bin/env bash

yarn install

if [ "$1" == "release" ]; then
  echo "release branch. set gitignore files for prod"
  git checkout release
	cp -f .gitignore.tags .gitignore
else
  echo "main branch. set gitignore files for dev"
  git checkout main
  cp -f .gitignore.main .gitignore
fi

yarn build
