#!/usr/bin/env bash

yarn install

if [ "$1" == "release" ]; then
  echo "release branch. set gitignore files for prod"
	cp -f .gitignore .gitignore.main
else
  echo "main branch. set gitignore files for dev"
  cp -f .gitignore .gitignore.tags
fi

yarn build
